# Generated by Django 3.1.2 on 2023-03-15 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20230315_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='tags',
        ),
    ]
